spring:
  application:
    name: hackathon
  datasource:
    url: jdbc:h2:tcp://localhost/~/kakaotest
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

app:
  jwt:
    issuer: "TrioGraphy"
    secret: "31a9bad0f91de7ca8fd3fede3f48c527f74f696300b8b28cc37682f6795fa952"
    access-ttl-seconds: 900
    refresh-ttl-seconds: 1209600

kakao:
  userinfo-uri: "https://kapi.kakao.com/v2/user/me"

#카카오 소셜 로그인 과정에서 액세스 토큰으로 사용자 정보를 조회할 때 쓰는 REST API 엔드포인트.
#
#구현 플로우 예시
#1. 프런트엔드에서 카카오 SDK 혹은 OAuth 토큰 엔드포인트로 로그인 진행
#2. 로그인 성공 후 발급된 액세스 토큰을 프런트엔드에서 받아 서버(백엔드)로 전송
#3. 백엔드에서 HTTP GET 요청으로  호출 - 헤더에 Authorization: Bearer {access_token} 포함
#4. 카카오가 반환한 사용자 ID, 이메일, 프로필 정보 등을 이용해 자체 회원 DB에 로그인·회원가입 처리

logging.level:
  org.hibernate.sql: debug